import { SearchResultObj } from "./customTypes";

export const DUMMY_RESULTS: SearchResultObj[] = [
  {
    product_url: "superthread.com",
    product_name: "Superthread",
    product_description:
      "Introducing Superthread: a task tracker with Integrated roadmaps, issues, and docs.\nMakes it easy for devs & non-devs to work together, which means no siloes.\nWhether you’re a founder, a lead, or an individual contributor, you can easily follow your work + It's fast!",
    product_image_file_name: "superthread-d-com.png",
    ph_source_url:
      "https://www.producthunt.com/products/superthread-tasks-docs-together",
    ph_count_follower: 744,
    ph_listed_at: "2023-06-07T09:38:48.465Z",
    ph_updated_at: "2023-06-07T09:38:48.465Z",
    sm_email: "cs@superthread.com",
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/Superthread_",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/superthread",
    sm_youtube: "https://www.youtube.com/channel/UCXb4dY7T2HlNdeVhzjAvgvg",
    sm_tiktok: null,
    sm_reddit: null,
  },
  {
    product_url: "ppcadlab.com",
    product_name: "PPC Ad Lab",
    product_description:
      "Get real-time Google Ads data from any location (even zip codes). Get all advertisers, ads, LSA's, shopping ads and more. White-label reporting and email outreach campaigns.",
    product_image_file_name: "ppcadlab-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/ppc-ad-lab",
    ph_count_follower: 12,
    ph_listed_at: "2022-04-14T09:42:32.136Z",
    ph_updated_at: "2022-04-14T09:42:32.136Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: "https://www.facebook.com/ppcadlab/",
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/ppcadlab",
    sm_youtube: "https://www.youtube.com/channel/UC7hg98_vhtZub1QuNYrs3PQ",
    sm_tiktok: null,
    sm_reddit: null,
  },
  {
    product_url: "recurpay.com",
    product_name: "Recurpay",
    product_description:
      "Subscriptions are convenient, managing them is not. Recurpay makes it much more easier for your customer to subscribe to their favourite product by bringing together a complete system where they can skip, cancel or edit their subscription at a single click.",
    product_image_file_name: "recurpay-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/recurpay",
    ph_count_follower: 3,
    ph_listed_at: "2022-04-14T09:13:03.136Z",
    ph_updated_at: "2022-04-14T09:13:03.136Z",
    sm_email: null,
    sm_instagram: "https://www.instagram.com/recurpay_subscriptions/",
    sm_facebook: "https://www.facebook.com/Recurpay.subscription",
    sm_twitter: "https://twitter.com/recurpay_io",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/recurpay",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
  },
  {
    product_url: "snappify.io",
    product_name: "snappify",
    product_description:
      "snappify helps you to create beautiful code snippets. It’s a design tool where you’re able to explain your code and style it to your needs. Have all your snippets stored in one place and easily share them with the rest of the world!",
    product_image_file_name: "snappify-d-io.png",
    ph_source_url: "https://www.producthunt.com/products/snappify",
    ph_count_follower: 126,
    ph_listed_at: "2022-04-14T09:42:29.006Z",
    ph_updated_at: "2022-04-14T09:42:29.006Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/snappify_io",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: "https://youtube.com/@snappify",
    sm_tiktok: null,
    sm_reddit: null,
  },
  {
    product_url: "neurosity.co",
    product_name: "Neurosity",
    product_description:
      "Every thought, feeling, and movement starts in your brain. Neurosity builds thought-powered devices that allow you to communicate and understand you.",
    product_image_file_name: "neurosity-d-co.png",
    ph_source_url: "https://www.producthunt.com/products/neurosity",
    ph_count_follower: 5,
    ph_listed_at: "2022-04-14T06:45:14.675Z",
    ph_updated_at: "2022-04-14T06:45:14.675Z",
    sm_email: null,
    sm_instagram: "https://instagram.com/neurosityco",
    sm_facebook: null,
    sm_twitter: "https://twitter.com/neurosity",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
  },
  {
    product_url: "memgraph.com",
    product_name: "Memgraph 1.0",
    product_description:
      "Memgraph is an in-memory graph database engineered to power real-time operational graph applications. Memgraph supports the Cypher and integrates deeply with the Python ecosystem to help you easily develop and deploy graph-based applications.",
    product_image_file_name: "memgraph-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/memgraph-1-0",
    ph_count_follower: 1,
    ph_listed_at: "2022-04-14T07:45:12.867Z",
    ph_updated_at: "2022-04-14T07:45:12.867Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/memgraphdb",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/memgraph/",
    sm_youtube: "https://www.youtube.com/@memgraph",
    sm_tiktok: null,
    sm_reddit: null,
  },
  {
    product_url: "sharly.ai",
    product_name: "Sharly AI",
    product_description:
      "Summarize fast and extract info from your documents - Sharly helps understand complex concept, transforming long PDFs into simple stories through a AI chatbot. Loved by over 1M+ professionals in US and CA, Sharly is free for everyone.",
    product_image_file_name: "sharly-d-ai.png",
    ph_source_url: "https://www.producthunt.com/products/sharly-ai",
    ph_count_follower: 147,
    ph_listed_at: "2024-01-18T01:13:03.251Z",
    ph_updated_at: "2024-01-18T01:13:03.251Z",
    sm_email: "simone@sharly.ai",
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/SharlyAI",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/sharly-ai/",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
  },
  {
    product_url: "yoast.com",
    product_name: "Yoast SEO Plugin",
    product_description:
      "Yoast helps you with your website's search engine optimization, with our internationally loved software and our online SEO courses.",
    product_image_file_name: "yoast-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/yoast-seo-plugin",
    ph_count_follower: 7,
    ph_listed_at: "2022-04-14T03:12:31.974Z",
    ph_updated_at: "2022-04-14T03:12:31.974Z",
    sm_email: null,
    sm_instagram: "https://www.instagram.com/yoast/",
    sm_facebook: "https://www.facebook.com/yoast/",
    sm_twitter: "https://twitter.com/yoast/",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/yoast-com/",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
  },
  {
    product_url: "wefaceswap.com",
    product_name: "Wefaceswap",
    product_description:
      "Discover Wefaceswap, a cloud-based faceswap service, where you can effortlessly transform photos, videos, and GIFs with just a few clicks. Experience the ease of realistic faceswapping online.",
    product_image_file_name: "wefaceswap-d-com.ico",
    ph_source_url: "https://www.producthunt.com/products/wefaceswap",
    ph_count_follower: 437,
    ph_listed_at: "2024-03-13T02:09:13.481Z",
    ph_updated_at: "2024-03-13T02:09:13.481Z",
    sm_email: "support@wefaceswap.com",
    sm_instagram: "https://www.instagram.com/wefaceswap_ai/",
    sm_facebook: "https://www.facebook.com/wefaceswap/",
    sm_twitter: "https://twitter.com/wefaceswap",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
  },
  {
    product_url: "stationdb.com",
    product_name: "StationDB",
    product_description:
      "StationDB is a no-code tool, that allows users to have an instant admin panel to view and modify their databases online. All editing actions are available with no necessary queries to implement them, and it can all be done in a collaborative way within a team.",
    product_image_file_name: "stationdb-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/stationdb",
    ph_count_follower: 2,
    ph_listed_at: "2022-04-13T15:18:17.562Z",
    ph_updated_at: "2022-04-13T15:18:17.562Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/stationdb",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
  },
];
